version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /apps/wallet
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
